version: '3.8'
services:
  web:
    image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    entrypoint: ["odoo", "--db_host", "db", "--db_port", "5432", "--db_user", "odoo", "--db_password", "odoo", "-d", "develop", "-i", "all,odoo_cribis", "--without-demo=none"]
    networks:
      - backend
      - traefik-public
    deploy:
      labels:
        - traefik.http.routers.${CI_PROJECT_NAME}-${CI_MERGE_REQUEST_IID}.rule=Host(`${CI_PROJECT_NAME}-${CI_MERGE_REQUEST_IID}-review.26house.com`)
        - traefik.http.services.${CI_PROJECT_NAME}-${CI_MERGE_REQUEST_IID}.loadbalancer.server.port=8069
        - traefik.enable=true
  db:
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    networks:
      - backend
networks:
  backend:
  traefik-public:
    external: true
