version: '3.8'

services:
  web:
    image: registry.gitlab.com/26house/odoo/modules/finance/h26_fin_partner_ares_autocomplete:manifest-update
    ports:
      - "8069:8069"
      - "8888:3001"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./:/mnt/extra-addons/odoo_cribis

    entrypoint: ["/usr/bin/python3", "-m", "ptvsd", "--host", "0.0.0.0", "--port", "3001", "/usr/bin/odoo", "--db_user=odoo", "--db_host=db", "--db_password=odoo"]

  db:
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:

