version: '3.8'
services:
  web:
    image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    entrypoint: ["odoo", "--db_host", "db", "--db_port", "5432", "--db_user", "odoo", "--db_password", "odoo", "-d", "tests", "--stop-after-init", "--init", "odoo_cribis", "--test-enable", "--test-tags", "odoo_cribis"]
  db:
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
